version: '3.8'
services:
  db:
    image: postgres:17
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: blog
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - '5432:5432'

  app:
    build:
      context: .
      target: builder
    command: npm run start:dev
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - '1313:1313'
    environment:
      DATABASE_HOST: host.docker.internal
      DATABASE_PORT: 5432
      DATABASE_USER: postgres
      DATABASE_PASSWORD: 12345
      DATABASE_NAME: blog
      JWT_SECRET: nkjfndkjfgdfjkgndkfjngalkmdflksmflkrl
volumes:
  db-data:
