name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  lint-test:
    name: Lint & Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm run test -- --runInBand

  build-and-push:
    name: Build & Push Docker Image
    needs: lint-test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and tag image
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/blog-app:latest .

      - name: Push image
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/blog-app:latest

  deploy:
    name: Trigger Render Deploy
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - name: Trigger deploy via Render API
        env:
          RENDER_API_KEY: ${{ secrets.RENDER_API_KEY }}
          SERVICE_ID: ${{ secrets.RENDER_SERVICE_ID }}
        run: |
          curl -X POST https://api.render.com/v1/services/$SERVICE_ID/deploys \
            -H "Authorization: Bearer $RENDER_API_KEY" \
            -H "Content-Type: application/json" \
            -d '{}'
